export const LOAD_REPOS = 'App/LOAD_REPOS';
export const LOAD_REPOS_SUCCESS = 'App/LOAD_REPOS_SUCCESS';
export const LOAD_REPOS_ERROR = 'App/LOAD_REPOS_ERROR';
export const REPOS_FILTER = 'App/REPOS_FILTER';

export const LICENSE_LOAD = 'App/LICENSE_LOAD';
export const LICENSE_LOAD_SUCCESS = 'App/LICENSE_LOAD_SUCCESS';
export const LICENSE_LOAD_ERROR = 'App/LICENSE_LOAD_ERROR';
export const LICENSE_FILTER = 'App/REPOS_LICENSE_FILTER';
